name: samparka
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.0.5
  emoji_picker_flutter: ^3.1.0
  internet_connection_checker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" # Use a square icon image (e.g., 1024x1024)
  adaptive_icon_background: "assets/icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon.png" # only available for Android 8.0 devices and above
 

flutter:
  uses-material-design: true

  assets:
    - assets/
